# Generated by Django 4.0.6 on 2022-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Department', models.CharField(max_length=25)),
            ],
        ),
    ]
