# Generated by Django 4.0.6 on 2022-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_project_department_remove_project_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Empid',
        ),
        migrations.AddField(
            model_name='project',
            name='createDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fileName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
