# Generated by Django 4.0.6 on 2022-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='persianTitle',
            field=models.CharField(default='', max_length=500),
        ),
    ]
